<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Pytest on jdhao's digital space</title><link>https://jdhao.github.io/tags/pytest/</link><description>Recent content in Pytest on jdhao's digital space</description><generator>Hugo -- gohugo.io</generator><language>en</language><copyright>© 2017 - 2025 ❤️ jdhao</copyright><lastBuildDate>Tue, 13 May 2025 18:28:20 +0200</lastBuildDate><atom:link href="https://jdhao.github.io/tags/pytest/index.xml" rel="self" type="application/rss+xml"/><item><title>Python system PATH issues When We Use Pytest</title><link>https://jdhao.github.io/2025/05/13/pytest_sys_path_issues/</link><pubDate>Tue, 13 May 2025 18:28:20 +0200</pubDate><guid>https://jdhao.github.io/2025/05/13/pytest_sys_path_issues/</guid><description>&lt;p>When I try to run &lt;code>pytest&lt;/code> locally for a Python project,
I noticed that the import in those test scripts may fail if I run &lt;code>pytest&lt;/code> in different directories.
The import error usually means that your actual code modules is not in the python path,
so they can not be imported successfully by your test scripts.&lt;/p>
&lt;p>This has something to do with how pytest set up the python path when you run it.&lt;/p></description></item><item><title>How to Filter Warnings in Python/pytest</title><link>https://jdhao.github.io/2025/03/05/python_filter_warnings/</link><pubDate>Wed, 05 Mar 2025 21:12:07 +0100</pubDate><guid>https://jdhao.github.io/2025/03/05/python_filter_warnings/</guid><description>&lt;p>When we are using 3rd packages in Python, we may see some warning messages.
For example, when you use the package BeautifulSoup and provide it with an url:&lt;/p></description></item></channel></rss>